apiVersion: apps/v1
kind: Deployment
metadata:
  name: myd
  labels:
    app: myd
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myd
    spec:
      containers:
        - image: registry.gitlab.com/buddhiprakash-jain/peerxp/newjava:latest
        imagePullPolicy: Always
        name: newjava
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 11
          periodSeconds: 11

---
apiVersion: v1
kind: Service
metadata:
  name: myd
spec:
  type: NodePort
  selector:
      app: myd
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
      targetPort: 8080
